@FirstQnAAPI_HostAddress = https://localhost:7189

GET {{FirstQnAAPI_HostAddress}}/api/group/1
Accept: application/json

###


GET {{FirstQnAAPI_HostAddress}}/api/Questions/
Accept: application/json


GET {{FirstQnAAPI_HostAddress}}/api/questionslist

###
